package com.bakery.api.user.dto;

import com.bakery.api.user.domain.User;
import com.bakery.api.user.dto.UserResponse;
import org.mapstruct.Mapper;

/**
 * DTO mapping is generated by MapStruct.
 *
 * ADR: docs/adr/0005-dto-mapping-mapstruct.md
 */
@Mapper(componentModel = "spring")
public interface UserMapper {

    UserResponse toResponse(User user);
}
