package com.bakery.bakeryapi.dto.user;

import com.bakery.bakeryapi.domain.User;
import org.mapstruct.Mapper;

/**
 * DTO mapping is generated by MapStruct.
 */
@Mapper(componentModel = "spring")
public interface UserMapper {

    UserResponse toResponse(User user);
}
